-- Login to PDB using pdbadmin

-- Create temp matches table
drop table temp_tgt_dbo.matches;
create table temp_tgt_dbo.matches(
match_id number primary key,
tournament varchar2(200),
gender varchar2(50),
match_type varchar2(20),
overs number,
match_date date,
team_1 varchar2(100),
team_2 varchar2(100),
venue varchar2(200),
city varchar2(100),
winner varchar2(100),
margin_type varchar2(100),
margin_number varchar2(100),
player_of_match varchar2(200),
toss_winner varchar2(100),
toss_decision varchar2(50),
umpire_1 varchar2(200),
umpire_2 varchar2(200),
rec_upd_tmst timestamp default systimestamp,
rec_upd_usr varchar2(50) default user
)
partition by range (match_date) interval (NUMTOYMINTERVAL(1,'MONTH'))
(PARTITION def_part VALUES LESS THAN (TO_DATE('01-JAN-2000', 'DD-MON-YYYY')));

grant select, insert, update, delete on temp_tgt_dbo.matches to cric_batch_user;
commit;
truncate table temp_tgt_dbo.matches; 
select * from TEMP_TGT_DBO.matches order by rec_upd_tmst desc;
select count(distinct match_id) from temp_tgt_dbo.matches;
select count(*) from temp_tgt_dbo.matches;

---------------------------------------------------------------------------------------------------------------------------
-- Create temporary tgt table for BBB data
drop table temp_tgt_dbo.bbb_data;
create table temp_tgt_dbo.bbb_data(
row_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
match_id number,
innings varchar2(50),
batting_team varchar2(50),
bowling_team varchar2(50),
ball number,
striker varchar2(100),
non_striker varchar2(100),
bowler varchar2(100),
runs_off_bat number,
extras number,
total_ball_runs number,
extras_type varchar2(20),
wicket_type varchar2(50),
player_dismissed varchar2(100),
rec_upd_tmst timestamp default systimestamp,
rec_upd_usr varchar2(50) default user
);

grant select, insert, update, delete on TEMP_TGT_DBO.bbb_data to cric_batch_user;
commit;
alter table temp_tgt_dbo.bbb_data add constraint bbb_pk PRIMARY KEY (row_id);

truncate table TEMP_TGT_DBO.bbb_data;
select * from TEMP_TGT_DBO.bbb_data order by rec_upd_tmst desc;
select count(*) from TEMP_TGT_DBO.bbb_data;
select count(distinct match_id) from TEMP_TGT_DBO.bbb_data;
-------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
create table temp_tgt_dbo.error_log(
match_id number,
error_msg varchar2(1000),
rec_upd_tmst timestamp default systimestamp,
rec_upd_usr varchar2(50) default user);

grant select, insert, update, delete on temp_tgt_dbo.error_log to cric_batch_user;
commit;
truncate table temp_tgt_dbo.error_log;
select * from temp_tgt_dbo.error_log;

delete temp_tgt_dbo.error_log where error_msg like '%strp%';
commit;
select distinct match_id from temp_tgt_dbo.bbb_data where match_id in (select match_id from TEMP_TGT_DBO.error_log);
----------------------------------------------------------------------------------------------------------------